---
- hosts: web
  became: true
  tasks:
        
   - name : copy the build artifacts of maven into tomcat webserver
     copy:
       src: /tmp/hello.war
       dest: /usr/apache-tomcat-8.5.35/webapps/
   - name: Stop tomcat server
     shell: /usr/local/bin/tomcatdown
       
    - name: restart tomcat server
      shell: /usr/local/bin/tomcatup
         
     

