---
- hosts: myweb
  become: true
  tasks:
    - name: ping
      command: echo "hi"

    - name: copy war to tomcat
      copy:
         src: /tmp/hello.war
         dest: /opt/apache-tomcat-8.5.35/webapps/

    - name: restart tomcat
      shell: /opt/apache-tomcat-8.5.35/bin/startup.sh
      register: std_out

    - debug : msg={{std_out}}
